### PR TITLE
keep tmux bash history

### PR DESCRIPTION
**Pull request by JasonGhent**
see: http://askubuntu.com/questions/339546/how-do-i-see-the-history-of-the-commands-i-have-run-in-tmux

### CODE REVIEW

**Comment by ratmav** [comment]
Thanks for the patch, @JasonGhent! If I understand this correctly, what we're doing here is merging the `tmux` history into the `bash` history, right? Does this work the other way as well?

**Comment by ratmav** [comment]
@JasonGhent why did you close this? You never responded to my question.

**Comment by JasonGhent** [comment]
It got caught in a flurry of PR activity with my primary org. Yeah, this merges the tmux bash history with the global bash history so that you can access your tmux bash history regardless of whether the tmux socket is still active.

**Comment by ratmav** [comment]
Cool! I'll re-open and merge.

**Pull request merged**
